permalink: /:year/:month/:day/:title
highlighter: rouge
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

title: a.blog.about.code
description: '{ topic: "code", type: "blog", author: "pan thomakos" }'
author: Pan Thomakos
github_username: panthomakos
twitter_username: panthomakos

aboutme_url: https://about.me/panthomakos
feedburner_rss_url: http://feeds.feedburner.com/ablogaboutcode
feedburner_email_url: http://feedburner.google.com/fb/a/mailverify?uri=ablogaboutcode&amp;loc=en_US
disqus:
  shortname: ablogaboutcode

feed:
  path: atom.xml

url: http://ablogaboutcode.com/

google_analytics: UA-28969585-1
