permalink: /:year/:month/:day/:title
auto: true
pygments : true

title : a.blog.about.code
tagline: '{ topic: "code", type: "blog", author: "pan thomakos" }'
author :
  name : Pan Thomakos
  github : panthomakos
  twitter : panthomakos

feedburner : ablogaboutcode

url: ablogaboutcode.com
