permalink: /:year/:month/:day/:title
auto: true
pygments : true
markdown : rdiscount

title : a.blog.about.code
tagline: '{ topic: "code", type: "blog", author: "pan thomakos" }'
author :
  name : Pan Thomakos
  github : panthomakos
  gems : 47511

feedburner : ablogaboutcode
disqus : ablogaboutcode

google :
  tracking_id : UA-28969585-1
